import {
  AlertTriangle,
  ArrowRight,
  ArrowUpRight,
  AtSign,
  Binary,
  BookHeart,
  Cable,
  Check,
  ChevronLeft,
  ChevronRight,
  CloudCog,
  Construction,
  Copy,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LoaderPinwheel,
  LucideIcon,
  Moon,
  MoreVertical,
  Plus,
  Puzzle,
  Search,
  Settings,
  SpellCheck,
  SquareActivity,
  SunMedium,
  TextSelect,
  Trash,
  User,
  WandSparkles,
  X,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  add: Plus,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  billing: CreditCard,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  check: Check,
  close: X,
  copy: Copy,
  ellipsis: MoreVertical,
  help: HelpCircle,
  laptop: Laptop,
  logo: Puzzle,
  media: Image,
  moon: Moon,
  page: File,
  post: FileText,
  search: Search,
  settings: Settings,
  spinner: Loader2,
  sun: SunMedium,
  trash: Trash,
  user: User,
  warning: AlertTriangle,
  design: WandSparkles,
  cloud: CloudCog,
  seo: SquareActivity,
  cms: TextSelect,
  development: Binary,
  maintenance: Construction,
  syntaxCheck: SpellCheck,
  mailServer: AtSign,
  checkConnection: Cable,
  catchAll: LoaderPinwheel,
};
