import React from 'react';
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from "@/components/ui/accordion"
import Section from "@/components/shared/section";
import HeaderSection from "@/components/shared/header-section";

const FaqSectionEmail = () => {
    return (
        <Section className="my-6">
                <HeaderSection
                    label="FAQ"
                    title="Questions & answers about email checker"
                    subtitle="Everything you need to know about how and why checking email addresses."
                />
                <Accordion type="single" collapsible className="w-full">
                    <AccordionItem value="item-1">
                        <AccordionTrigger>How to use email checker</AccordionTrigger>
                        Email checker is a free, easy to use and simple tool. Just enter the email address and click on Verify. We will then proceed with several checks to verify the email address and flag it as valid or invalid.
                    </AccordionItem>
                    <AccordionItem value="item-2">
                        <AccordionTrigger>What is an email checker?</AccordionTrigger>
                        <AccordionContent>
                            Email checker is a free tool to verify anyone&apos;s email address. It validates that the email address is well formed, not from a disposable email service and that the email address is technically well-configured (MX records are present, SMTP mailbox replies successfully). In case we detect something wrong, the email address will be flagged as invalid.
                        </AccordionContent>
                    </AccordionItem>
                    <AccordionItem value="item-3">
                        <AccordionTrigger>How does an email verifier work?</AccordionTrigger>
                        <AccordionContent>
                            Email checker proceeds with several checks to determine if an email address is valid:

                            The email address must be well formed (e.g. {"firstname.lastname"}@{"domain"}).
                            It should not be generated by a disposable email service (such as abc.com).
                            The MX records should be present on DNS.
                            An SMTP server should run for the domain.
                            A mailbox with that email address should exists on the SMTP server.

                            Depending on the provided email address, we might apply extra-checks on a per basis.
                        </AccordionContent>
                    </AccordionItem>
                </Accordion>
        </Section>
    );
};

export default FaqSectionEmail;